apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysql-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: mysql
          servicePort: 3306
